### ISSUE TITLE
Trumbowyg plugin: shows the html-tags after update a post/page

### ISSUE THREAD

**Issue by ctuxboy** [BoidCMS/trumbowyg#1]
When **create** a post/page, it works good, but after **update** a post/page then it shows all the html-tags in the content, so the layout from the content is broken.
See this [link](https://boid.gewoonsimpel.be/huidig-jaartal-tonen-met-php)

EDIT: using the standard themes.

**Comment by sysadev** [comment]
Thanks @ctuxboy for taking a deep look. But can you suggest what possibly cause it?

**Comment by ctuxboy** [comment]
> Thanks @ctuxboy for taking a deep look. But can you suggest what possibly cause it?

At this moment, i don't know. In the coming days, i try a clean install and hope it solved the problem.

I will keep you informed
